version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - node-network  
    tty: true
    container_name: reverse-proxy
    ports:
      - "8080:80" 
    depends_on:
      - app

  app:
    build: 
      context: node
      dockerfile: Dockerfile
    networks:
      - node-network
    volumes:
      - ./node:/app
      - /app/node_modules
    tty: true
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db 

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
     
networks:
  node-network:
    driver: bridge
